ALTER TABLE warehouse ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE room ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE rack ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE shelf ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE pallet ADD COLUMN deleted_at TIMESTAMP;
