ALTER TABLE vendor ADD COLUMN vendor_category VARCHAR(50);
ALTER TABLE vendor ADD COLUMN gstin VARCHAR(15);
ALTER TABLE vendor ADD COLUMN pan VARCHAR(10);
ALTER TABLE vendor ADD COLUMN website VARCHAR(255);
ALTER TABLE vendor ADD COLUMN payment_terms_days INTEGER;
