ALTER TABLE qc_sample ADD COLUMN IF NOT EXISTS retained_flag BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE qc_sample ADD COLUMN IF NOT EXISTS retained_quantity NUMERIC(18,3);
ALTER TABLE qc_sample ADD COLUMN IF NOT EXISTS retained_until DATE;
