ALTER TABLE material ADD COLUMN IF NOT EXISTS status VARCHAR(50);

UPDATE material
SET status = COALESCE(status, CASE WHEN COALESCE(is_active, FALSE) THEN 'ACTIVE' ELSE 'OBSOLETE' END)
WHERE status IS NULL;

ALTER TABLE material ALTER COLUMN status SET NOT NULL;
