package com.batchsphere.core.lims.equipment.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@ActiveProfiles("test")
class EquipmentControllerIntegrationTest {

    @Autowired
    private WebApplicationContext webApplicationContext;

    private MockMvc mockMvc;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
                .apply(springSecurity())
                .build();
    }

    @Test
    void createsEquipmentWithAutoGeneratedId() throws Exception {
        String token = loginAsAdmin();

        MvcResult result = createEquipment(token, "HPLC");
        assertEquals(200, result.getResponse().getStatus(), result.getResponse().getContentAsString());

        JsonNode equipment = objectMapper.readTree(result.getResponse().getContentAsString());
        assertTrue(equipment.get("equipmentId").asText().startsWith("EQ-"),
                "equipmentId should start with EQ-: " + equipment.get("equipmentId").asText());
        assertEquals("PENDING_QUALIFICATION", equipment.get("status").asText());
        assertNotNull(equipment.get("id").asText());
    }

    @Test
    void approvedPqRecordActivatesEquipment() throws Exception {
        String token = loginAsAdmin();

        JsonNode equipment = objectMapper.readTree(createEquipment(token, "BALANCE").getResponse().getContentAsString());
        String equipmentId = equipment.get("id").asText();

        MvcResult qualResult = mockMvc.perform(post("/api/equipment/{id}/qualifications", equipmentId)
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "qualificationType": "PQ",
                                  "protocolReference": "PQ-BAL-2026-001",
                                  "performedBy": "qc.analyst",
                                  "performedAt": "%s",
                                  "result": "PASS",
                                  "nextRequalificationDue": "%s",
                                  "username": "admin",
                                  "password": "Admin@123",
                                  "signatureMeaning": "I certify PQ completion"
                                }
                                """.formatted(LocalDate.now(), LocalDate.now().plusYears(1))))
                .andReturn();
        assertEquals(200, qualResult.getResponse().getStatus(), qualResult.getResponse().getContentAsString());

        MvcResult equipResult = mockMvc.perform(get("/api/equipment/{id}", equipmentId)
                        .header("Authorization", "Bearer " + token))
                .andReturn();
        assertEquals(200, equipResult.getResponse().getStatus(), equipResult.getResponse().getContentAsString());
        JsonNode updated = objectMapper.readTree(equipResult.getResponse().getContentAsString());
        assertEquals("ACTIVE", updated.get("status").asText());
    }

    @Test
    void failedQualificationSetsUnderMaintenance() throws Exception {
        String token = loginAsAdmin();

        JsonNode equipment = objectMapper.readTree(createEquipment(token, "GC").getResponse().getContentAsString());
        String equipmentId = equipment.get("id").asText();

        MvcResult qualResult = mockMvc.perform(post("/api/equipment/{id}/qualifications", equipmentId)
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "qualificationType": "IQ",
                                  "protocolReference": "IQ-GC-2026-001",
                                  "performedBy": "qc.analyst",
                                  "performedAt": "%s",
                                  "result": "FAIL",
                                  "deviationNoted": "Temperature excursion observed during IQ"
                                }
                                """.formatted(LocalDate.now())))
                .andReturn();
        assertEquals(200, qualResult.getResponse().getStatus(), qualResult.getResponse().getContentAsString());

        MvcResult equipResult = mockMvc.perform(get("/api/equipment/{id}", equipmentId)
                        .header("Authorization", "Bearer " + token))
                .andReturn();
        assertEquals(200, equipResult.getResponse().getStatus(), equipResult.getResponse().getContentAsString());
        JsonNode updated = objectMapper.readTree(equipResult.getResponse().getContentAsString());
        assertEquals("UNDER_MAINTENANCE", updated.get("status").asText());
    }

    @Test
    void getSummaryReturnsStructuredResponse() throws Exception {
        String token = loginAsAdmin();

        MvcResult result = mockMvc.perform(get("/api/equipment/summary")
                        .header("Authorization", "Bearer " + token))
                .andReturn();
        assertEquals(200, result.getResponse().getStatus(), result.getResponse().getContentAsString());

        JsonNode summary = objectMapper.readTree(result.getResponse().getContentAsString());
        assertNotNull(summary.get("totalActive"), "summary should contain totalActive field");
        assertNotNull(summary.get("pendingQualification"));
        assertNotNull(summary.get("underMaintenance"));
        assertNotNull(summary.get("calibrationDueSoon"));
        assertNotNull(summary.get("qualificationDueSoon"));
    }

    private MvcResult createEquipment(String token, String type) throws Exception {
        return mockMvc.perform(post("/api/equipment")
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "name": "Test %s Unit",
                                  "equipmentType": "%s",
                                  "location": "QC Lab A",
                                  "manufacturer": "Agilent",
                                  "model": "Series 1200",
                                  "serialNumber": "SN-%s-%d",
                                  "calibrationIntervalMonths": 12,
                                  "responsibleAnalyst": "qc.analyst"
                                }
                                """.formatted(type, type, type, System.currentTimeMillis())))
                .andReturn();
    }

    private String loginAsAdmin() throws Exception {
        MvcResult loginResult = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "username": "admin",
                                  "password": "Admin@123"
                                }
                                """))
                .andReturn();
        assertEquals(200, loginResult.getResponse().getStatus(), loginResult.getResponse().getContentAsString());
        return objectMapper.readTree(loginResult.getResponse().getContentAsString()).get("accessToken").asText();
    }
}
