package com.batchsphere.core.qms.complaint.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

import java.time.LocalDate;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
@ActiveProfiles("test")
class ComplaintControllerIntegrationTest {

    @Autowired
    private WebApplicationContext webApplicationContext;

    private MockMvc mockMvc;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
                .apply(springSecurity())
                .build();
    }

    @Test
    void createsComplaintWithAutoGeneratedNumber() throws Exception {
        String token = loginAsAdmin();

        MvcResult result = mockMvc.perform(post("/api/complaints")
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "description": "Customer reported foreign particle in blister pack.",
                                  "receivedDate": "%s",
                                  "source": "CUSTOMER",
                                  "category": "PRODUCT_QUALITY",
                                  "severity": "CRITICAL",
                                  "productName": "Paracetamol 500mg",
                                  "lotNumber": "LOT-2026-001",
                                  "reportedBy": "John Smith"
                                }
                                """.formatted(LocalDate.now())))
                .andReturn();

        assertEquals(200, result.getResponse().getStatus(), result.getResponse().getContentAsString());
        JsonNode complaint = objectMapper.readTree(result.getResponse().getContentAsString());
        assertNotNull(complaint.get("id").asText());
        assertTrue(complaint.get("complaintNumber").asText().startsWith("COMP-"),
                "Expected complaint number to start with COMP- but got: " + complaint.get("complaintNumber").asText());
        assertEquals("RECEIVED", complaint.get("status").asText());
        assertEquals("CRITICAL", complaint.get("severity").asText());
        assertEquals("CUSTOMER", complaint.get("source").asText());
    }

    @Test
    void closureRequiresESignatureAndPendingClosureStatus() throws Exception {
        String token = loginAsAdmin();

        MvcResult createResult = mockMvc.perform(post("/api/complaints")
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "description": "Labeling error found on exported batch.",
                                  "receivedDate": "%s",
                                  "source": "DISTRIBUTOR",
                                  "category": "LABELING_ERROR",
                                  "severity": "MAJOR"
                                }
                                """.formatted(LocalDate.now())))
                .andReturn();
        assertEquals(200, createResult.getResponse().getStatus(), createResult.getResponse().getContentAsString());
        String complaintId = objectMapper.readTree(createResult.getResponse().getContentAsString()).get("id").asText();

        MvcResult blockedClose = mockMvc.perform(put("/api/complaints/{id}/status", complaintId)
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "status": "CLOSED",
                                  "closureSummary": "Resolved after investigation.",
                                  "username": "admin",
                                  "password": "Admin@123"
                                }
                                """))
                .andReturn();
        assertEquals(409, blockedClose.getResponse().getStatus(),
                "Expected 409 when closing without PENDING_CLOSURE status, got: " + blockedClose.getResponse().getContentAsString());
    }

    @Test
    void linkToNonExistentDeviationReturns404() throws Exception {
        String token = loginAsAdmin();

        MvcResult createResult = mockMvc.perform(post("/api/complaints")
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "description": "Adverse event report received from clinical site.",
                                  "receivedDate": "%s",
                                  "source": "CLINICAL",
                                  "category": "ADVERSE_EVENT",
                                  "severity": "CRITICAL"
                                }
                                """.formatted(LocalDate.now())))
                .andReturn();
        assertEquals(200, createResult.getResponse().getStatus(), createResult.getResponse().getContentAsString());
        String complaintId = objectMapper.readTree(createResult.getResponse().getContentAsString()).get("id").asText();

        MvcResult linkResult = mockMvc.perform(post("/api/complaints/{id}/link-deviation", complaintId)
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "deviationId": "%s"
                                }
                                """.formatted(UUID.randomUUID())))
                .andReturn();
        assertEquals(404, linkResult.getResponse().getStatus(),
                "Expected 404 for non-existent deviation, got: " + linkResult.getResponse().getContentAsString());
    }

    @Test
    void getSummaryReturnsCorrectCounts() throws Exception {
        String token = loginAsAdmin();

        mockMvc.perform(post("/api/complaints")
                        .header("Authorization", "Bearer " + token)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "description": "Packaging defect reported by market surveillance.",
                                  "receivedDate": "%s",
                                  "source": "MARKET",
                                  "category": "PACKAGING_DEFECT",
                                  "severity": "MINOR"
                                }
                                """.formatted(LocalDate.now())))
                .andReturn();

        MvcResult summaryResult = mockMvc.perform(get("/api/complaints/summary")
                        .header("Authorization", "Bearer " + token))
                .andReturn();
        assertEquals(200, summaryResult.getResponse().getStatus(), summaryResult.getResponse().getContentAsString());
        JsonNode summary = objectMapper.readTree(summaryResult.getResponse().getContentAsString());
        assertNotNull(summary.get("countsByStatus"), "Expected countsByStatus in summary response");
        assertNotNull(summary.get("countsByCategory"), "Expected countsByCategory in summary response");
        assertNotNull(summary.get("countsBySeverity"), "Expected countsBySeverity in summary response");
        assertTrue(summary.get("countsByStatus").get("RECEIVED").asLong() >= 1,
                "Expected at least one RECEIVED complaint in summary");
    }

    private String loginAsAdmin() throws Exception {
        MvcResult loginResult = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "username": "admin",
                                  "password": "Admin@123"
                                }
                                """))
                .andReturn();
        assertEquals(200, loginResult.getResponse().getStatus(), loginResult.getResponse().getContentAsString());
        return objectMapper.readTree(loginResult.getResponse().getContentAsString()).get("accessToken").asText();
    }
}
